// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "go-zero-admin-server/api/internal/handler/login"
	user "go-zero-admin-server/api/internal/handler/user"
	"go-zero-admin-server/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/api/login",
				Handler: login.LoginHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/admin/api/user",
				Handler: user.GetUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/api/user",
				Handler: user.AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/admin/api/user/:id",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/admin/api/user/:id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
		},
	)
}
