// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	jwt "go-zero-admin-server/api/internal/handler/jwt"
	search "go-zero-admin-server/api/internal/handler/search"
	user "go-zero-admin-server/api/internal/handler/user"
	verify "go-zero-admin-server/api/internal/handler/verify"
	"go-zero-admin-server/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/api/rjwt",
				Handler: jwt.RefreshJwtHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/api/djwt",
				Handler: jwt.DecodeJwtHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/admin/api/search/userId/:id",
				Handler: search.GetUserByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/api/search/username/:username",
				Handler: search.GetUserByUserNameLikeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/api/search/roles",
				Handler: search.GetAllRolesHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/api/verify/login",
				Handler: verify.LoginHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/admin/api/user",
				Handler: user.GetUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/api/user",
				Handler: user.AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/admin/api/user/:id",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/admin/api/userRoles/:id",
				Handler: user.EditUserRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/admin/api/user/:id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
