// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"go-zero-admin-server/service/admin/user/rpc/internal/logic"
	"go-zero-admin-server/service/admin/user/rpc/internal/svc"
	"go-zero-admin-server/service/admin/user/rpc/user"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) GetUserById(ctx context.Context, in *user.IDReq) (*user.UserReply, error) {
	l := logic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

func (s *UserRpcServer) GetUserByUsername(ctx context.Context, in *user.UsernameReq) (*user.UserReply, error) {
	l := logic.NewGetUserByUsernameLogic(ctx, s.svcCtx)
	return l.GetUserByUsername(in)
}
