// Code generated by goctl. DO NOT EDIT!
// Source: vip.proto

package server

import (
	"context"

	"go-zero-admin-server/service/vip/rpc/internal/logic"
	"go-zero-admin-server/service/vip/rpc/internal/svc"
	"go-zero-admin-server/service/vip/rpc/vip"
)

type VipServer struct {
	svcCtx *svc.ServiceContext
}

func NewVipServer(svcCtx *svc.ServiceContext) *VipServer {
	return &VipServer{
		svcCtx: svcCtx,
	}
}

func (s *VipServer) GetVipById(ctx context.Context, in *vip.IdReq) (*vip.VipInfoReply, error) {
	l := logic.NewGetVipByIdLogic(ctx, s.svcCtx)
	return l.GetVipById(in)
}

func (s *VipServer) GetVipByCardNumberLike(ctx context.Context, in *vip.CardNumberReq) (*vip.VipsInfoReply, error) {
	l := logic.NewGetVipByCardNumberLikeLogic(ctx, s.svcCtx)
	return l.GetVipByCardNumberLike(in)
}

func (s *VipServer) IsExistVipById(ctx context.Context, in *vip.IdReq) (*vip.IsExistReply, error) {
	l := logic.NewIsExistVipByIdLogic(ctx, s.svcCtx)
	return l.IsExistVipById(in)
}

func (s *VipServer) IsExistVipByCardNumber(ctx context.Context, in *vip.CardNumberReq) (*vip.IsExistReply, error) {
	l := logic.NewIsExistVipByCardNumberLogic(ctx, s.svcCtx)
	return l.IsExistVipByCardNumber(in)
}

func (s *VipServer) GetVips(ctx context.Context, in *vip.VipsReq) (*vip.VipsInfoReply, error) {
	l := logic.NewGetVipsLogic(ctx, s.svcCtx)
	return l.GetVips(in)
}

func (s *VipServer) AddVip(ctx context.Context, in *vip.VipAddReq) (*vip.IsSuccessReply, error) {
	l := logic.NewAddVipLogic(ctx, s.svcCtx)
	return l.AddVip(in)
}

func (s *VipServer) UpdateVip(ctx context.Context, in *vip.VipUpdateReq) (*vip.IsSuccessReply, error) {
	l := logic.NewUpdateVipLogic(ctx, s.svcCtx)
	return l.UpdateVip(in)
}

func (s *VipServer) DelVip(ctx context.Context, in *vip.IdReq) (*vip.IsSuccessReply, error) {
	l := logic.NewDelVipLogic(ctx, s.svcCtx)
	return l.DelVip(in)
}

func (s *VipServer) DelSomeVip(ctx context.Context, in *vip.IdsReq) (*vip.IsSuccessReply, error) {
	l := logic.NewDelSomeVipLogic(ctx, s.svcCtx)
	return l.DelSomeVip(in)
}
