// Code generated by goctl. DO NOT EDIT.
package types

type Reply struct {
	Code int                    `json:"code"`
	Data map[string]interface{} `json:"data"`
	Msg  string                 `json:"msg"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type GetUsersReq struct {
	Page     int    `form:"page,default=1"`
	Limit    int    `form:"limit,default=10"`
	Username string `form:"username,optional"`
}

type AddUserReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Info     string `json:"info,optional"`
}

type UpdateUserReq struct {
	Id       uint   `path:"id"`
	Password string `json:"password,optional"`
	Info     string `json:"info,optional"`
}

type DeleteUserReq struct {
	Id uint `path:"id"`
}

type IdReq struct {
	Id uint `path:"id"`
}

type UsernameReq struct {
	Username string `path:"username"`
}
